name: App Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  PROJECT_APP_NAME: ArquetipoRNTSFS
  BUILDING_APP_NAME: app-release

jobs:

  variables:
    name: Variables test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get variables
        run: |
          echo ${{ env.PROJECT_APP_NAME }}-${{ env.BUILDING_APP_NAME }}

  # android:
  #   name: Publish Android
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       node-version: [12.x]
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: Use Node ${{ matrix.node-version }}
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: ${{ matrix.node-version }}
  #     - run: |
  #         npm install
  #     - name: Building Android
  #       run: |
  #         cd android
  #         chmod +x gradlew
  #         sh gradlew assembleRelease
  #     - name: Get app version
  #       id: package-version
  #       uses: martinbeentjes/npm-get-version-action@master
  #     - name: Upload Artifact
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: app-release-v${{ steps.package-version.outputs.current-version }}.apk
  #         path: android/app/build/outputs/apk/release/*.apk

  # ios:
  #   name: Publish iOS
  #   runs-on: macos-latest
  #   strategy:
  #     matrix:
  #       node-version: [12.x]
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: Use Node ${{ matrix.node-version }}
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: ${{ matrix.node-version }}
  #     - run: |
  #         npm install
  #     - name: Install pod dependencies
  #       run: |
  #         cd ios && pod install
  #     - name: Building iOS
  #       run: |
  #         ls       
  #         xcodebuild -workspace ./ios/testing_project.xcworkspace -scheme testing_project archive -archivePath ./ios/testing_project.xcarchive -allowProvisioningUpdates
  #         xcodebuild -exportArchive -archivePath ./ios/testing_project.xcarchive -exportPath . -exportOptionsPlist testing_project/Info.plist
  #         mv testing_project.ipa ../testing_project.ipa
  #     - name: Get app version
  #       id: package-version
  #       uses: martinbeentjes/npm-get-version-action@master
  #     - name: Upload Artifact
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: app-release-v${{ steps.package-version.outputs.current-version }}.ipa
  #         path: ios/build/

