name: App Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  PROJECT_APP_NAME: ArquetipoRNTSFS
  BUILDING_APP_NAME: app-release

jobs:

  # android:
  #   name: Publish Android
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       node-version: [12.x]
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: Use Node ${{ matrix.node-version }}
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: ${{ matrix.node-version }}
  #     - run: |
  #         npm install
  #     - name: Building Android
  #       run: |
  #         cd android
  #         chmod +x gradlew
  #         sh gradlew assembleRelease
  #     - name: Get app version
  #       id: package-version
  #       uses: martinbeentjes/npm-get-version-action@master
  #     - name: Upload Artifact
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: ${{ env.BUILDING_APP_NAME }}-android-v${{ steps.package-version.outputs.current-version }}.apk
  #         path: android/app/build/outputs/apk/release/*.apk

  ios:
    name: Publish iOS
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          npm install
      - name: Install pod dependencies
        run: |
          cd ios && pod install
      - name: Building iOS
        run: |
          ls       
          xcodebuild -workspace ./ios/${{ env.PROJECT_APP_NAME }}.xcworkspace -scheme ${{ env.PROJECT_APP_NAME }} archive -archivePath ./ios/${{ env.PROJECT_APP_NAME }}.xcarchive -allowProvisioningUpdates
          xcodebuild -exportArchive -archivePath ./ios/${{ env.PROJECT_APP_NAME }}.xcarchive -exportPath . -exportOptionsPlist ${{ env.PROJECT_APP_NAME }}/Info.plist
          mv ${{ env.PROJECT_APP_NAME }}.ipa ../${{ env.PROJECT_APP_NAME }}.ipa
      - name: Get app version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.BUILDING_APP_NAME }}-ios-v${{ steps.package-version.outputs.current-version }}.ipa
          path: ios/build/

